[package]
name = "orpheus"
version = "0.1.0"
edition = "2021"

[lib]
name = "_core"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
async-std = "1.13.0"
futures-lite = "2.5.0"
isahc = { version = "1.7.2", features = ["json"] }
# "extension-module" tells pyo3 we want to build an extension module (skips linking against libpython.so)
# "abi3-py39" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.9
pyo3 = { version = "0.23.3", features = [
  "extension-module",
  "abi3-py39",
  "experimental-async",
] }
pyo3-async-runtimes = { version = "0.23.0", features = ["async-std"] }
pythonize = "0.23.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
serde_with = { version = "3.12.0", features = ["json"] }
url = "2.5.4"
