[package]
name = "orpheus"
version = "0.1.0"
edition = "2021"
description = "A blazing fast OpenRouter SDK"
license = "MIT"

[lib]
name = "orpheus"
crate-type = ["cdylib", "rlib"]

[features]
default = []
python = ["dep:pyo3", "dep:pyo3-async-runtimes", "dep:pythonize"]
anyhow = ["dep:anyhow"]
mcp = ["dep:rmcp", "tokio/rt-multi-thread"]

[dependencies]
anyhow = { version = "1.0.98", optional = true }
bon = "3.6.3"
bytes = "1.10.1"
futures-lite = "2.6.0"
pyo3 = { version = "0.24.0", optional = true, features = [
    "extension-module",
    "abi3-py39",
    "experimental-async",
    "either",
    "serde",
    "smallvec",
    "anyhow",
    "multiple-pymethods",
] }
pyo3-async-runtimes = { version = "0.24.0", optional = true, features = [
    "tokio-runtime",
] }
pythonize = { version = "0.24.0", optional = true }
reqwest = { version = "0.12.12", features = [
    "json",
    "blocking",
    "rustls-tls",
    "stream",
] }
rmcp = { version = "0.2.1", optional = true, features = [
    "client",
    "transport-child-process",
] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
serde_with = { version = "3.12.0", features = ["json"] }
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["rt", "macros"] }
url = "2.5.4"

[dev-dependencies]
colored = "3.0.0"
rand = "0.9.1"
tokio = { version = "1.44.1", features = ["full"] }
