[tasks.develop_and_test]
description = "Build with maturin and run all tests"
run = "uv run maturin develop --uv && uv run pytest -v"

[tasks.dev]
description = "Build with maturin"
run = "uv run maturin develop --uv"

[tasks.test]
description = "Run all tests"
run = "uv run pytest -v"
