[tasks.develop]
description = "Build with maturin"
run = "uv run maturin develop --uv"
alias = ["d", "dev"]

[tasks.test]
wait_for = "develop"
description = "Run specificied tests"
run = 'uv run pytest -v {{arg(name="path", default="tests")}}'
alias = ["t"]

[tasks.benchmark]
wait_for = "develop"
description = "Run sync benchmark"
run = 'uv run scripts/benchmark.py -r {{option(name="runs", default="1000")}}'
alias = ["b", "bench"]

[tasks.async-benchmark]
wait_for = "develop"
description = "Run async benchmark"
run = 'uv run scripts/async_benchmark.py -r {{option(name="runs", default="1000")}}'
alias = ["ab", "abench"]
