[project]
name = "orpheus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "ajac-zero", email = "ajcardoza2000@gmail.com" }]
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = ["pytest>=8.3.4"]

[tool.maturin]
module-name = "orpheus._core"
python-packages = ["orpheus"]
python-source = "python"

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
