use serde::{Deserialize, Serialize};

use super::ChatMessage;

#[serde_with::skip_serializing_none]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatResponse {
    /// Unique identifier for the chat completion
    pub id: Option<String>,

    /// List of chat completion choices
    pub choices: Option<Vec<ChatChoice>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatChoice {
    /// The message generated by the model
    pub message: Option<ChatMessage>,
}
